
on: [push]

permissions: read-all

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  # AWS_REGION: 'us-west-2'
  # AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GH_PAT: ${{ secrets.GH_PAT }}
  TG_VERSION: 0.59.7
  TG_VER: '0.59.7'
  TF_VERSION: 1.9.2 
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  working_dir: './dev/us-west-2' 


jobs:

  tg_plan_dev:
      name: 'Terragrunt Plan Dev'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@master
        - name: Terragrunt Plan Dev
          uses: ./.github/actions/terragrunt-action
          with:
            gh_pat: ${{ env.GH_PAT }} 
            tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }} 
            tf_version: ${{ env.TF_VERSION }}
            tg_version: ${{ env.TG_VERSION }}
            tg_ver: ${{ env.TG_VER }}
            environment_name: "dev"
            
  # tg_apply_dev:
  #     name: 'Terragrunt Apply Dev'
  #     runs-on: ubuntu-latest
  #     needs: tg_plan_dev
  #     if: github.ref == 'refs/heads/develop'
  #     steps:
  #       - name: Checkout repo
  #         uses: actions/checkout@master
  #       - name: Terragrunt Apply Dev
  #         uses: gruntwork-io/terragrunt-action@v2
  #         with:
  #           tf_version: ${{ env.TF_VERSION }}
  #           tg_version: ${{ env.TG_VERSION }}
  #           tg_dir: ${{ env.working_dir }}
  #           tg_command: 'run-all apply --terragrunt-log-level debug'



#   7.575Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:27.575Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:27.575Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:27.575Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:30.592Z","logger":"controller","message":"skipping, unable to resolve instance types","commit":"490ef94","controller":"provisioner","NodePool":{"name":"default"},"error":"no subnets found"}                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:30.592Z","logger":"controller","message":"could not schedule pod","commit":"490ef94","controller":"provisioner","Pod":{"name":"cert-manager-startupapicheck-ddzqp","namespace":"cert-manager"},"error":"all available instance types exceed limits for nodepool: \"default\""}                                                                                                      │
# │ {"level":"ERROR","time":"2025-02-09T20:39:37.576Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:37.576Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:37.576Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:37.576Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:37.576Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:37.576Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:40.593Z","logger":"controller","message":"skipping, unable to resolve instance types","commit":"490ef94","controller":"provisioner","NodePool":{"name":"default"},"error":"no subnets found"}                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:40.594Z","logger":"controller","message":"could not schedule pod","commit":"490ef94","controller":"provisioner","Pod":{"name":"cert-manager-startupapicheck-ddzqp","namespace":"cert-manager"},"error":"all available instance types exceed limits for nodepool: \"default\""}                                                                                                      │
# │ {"level":"ERROR","time":"2025-02-09T20:39:47.578Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                                                                                                                                                                       │
# │ {"level":"ERROR","time":"2025-02-09T20:39:47.578Z","logger":"controller","message":"failed listing instance types for default","commit":"490ef94","controller":"disruption","error":"no subnets found"}                                                                        