
on: [push]

permissions: read-all

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  # AWS_REGION: 'us-west-2'
  # AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GH_PAT: ${{ secrets.GH_PAT }}
  TG_VERSION: 0.59.7
  TG_VER: '0.59.7'
  TF_VERSION: '1.9.2' 
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  working_dir: './dev/us-west-2' 


jobs:

  tg_plan_dev:
      name: 'Terragrunt Plan Dev'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@master
        - name: Terragrunt Plan Dev
          uses: ./.github/actions/terragrunt-action
          with:
            gh_pat: ${{ env.GH_PAT }} 
            tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }} 
            tf_version: ${{ env.TF_VERSION }}
            tg_version: ${{ env.TG_VERSION }}
            tg_ver: ${{ env.TG_VER }}
            environment_name: "dev"
            
  tg_apply_dev:
      name: 'Terragrunt Apply Dev'
      runs-on: ubuntu-latest
      needs: tg_plan_dev
      environment: dev
      if: github.ref == 'refs/heads/develop'
      steps:
        - name: Checkout repo
          uses: actions/checkout@master
        - name: Terragrunt Apply Dev
          uses: ./.github/actions/terragrunt-action
          with:
            tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }} 
            tf_version: ${{ env.TF_VERSION }}
            tg_version: ${{ env.TG_VERSION }}
            tg_ver: ${{ env.TG_VER }}
            environment_name: "dev"          
            apply: true